services:
  meshcord:
    image: ghcr.io/sargonas/meshcord:latest
    container_name: meshcord-bot
    restart: unless-stopped
    
    # Environment variables - REQUIRED: Set these values
    environment:
      # Discord Configuration (REQUIRED)
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_CHANNEL_ID: ${DISCORD_CHANNEL_ID}
      
      # Serial Configuration
      SERIAL_PORT: ${SERIAL_PORT:-/dev/ttyUSB0}
      
      # Serial Connection Health Monitoring
      SERIAL_TIMEOUT: ${SERIAL_TIMEOUT:-240}
      
      # Message Filtering (optional - defaults shown)
      SHOW_TEXT_MESSAGES: ${SHOW_TEXT_MESSAGES:-true}
      SHOW_POSITION_UPDATES: ${SHOW_POSITION_UPDATES:-true}
      SHOW_NODE_INFO: ${SHOW_NODE_INFO:-true}
      SHOW_TELEMETRY: ${SHOW_TELEMETRY:-true}
      SHOW_ROUTING: ${SHOW_ROUTING:-false}
      SHOW_ADMIN: ${SHOW_ADMIN:-true}
      SHOW_DETECTION_SENSOR: ${SHOW_DETECTION_SENSOR:-true}
      SHOW_RANGE_TEST: ${SHOW_RANGE_TEST:-true}
      SHOW_STORE_FORWARD: ${SHOW_STORE_FORWARD:-true}
      SHOW_UNKNOWN: ${SHOW_UNKNOWN:-false}
      
      # Signal strength reporting (optional)
      SHOW_SIGNAL_STRENGTH: ${SHOW_SIGNAL_STRENGTH:-true}
      
      # Debug mode (optional)
      DEBUG_MODE: ${DEBUG_MODE:-false}
    
    # Volumes for persistent data
    volumes:
      - meshcord_data:/app/data
      
    # Device access for serial connection (REQUIRED)
    devices:
      - ${SERIAL_DEVICE:-/dev/ttyUSB0}:${SERIAL_PORT:-/dev/ttyUSB0}
    
    # Logging configuration

volumes:
  meshcord_data:
    external: true #if using data persistence
